Popup page
Bushido-brown/My-Portfolio2 pull request #8
Opened 2022-05-12 22:26 UTC by Bushido-brown

I used script.js to create a popup window for my portfolio.

2022-05-12 23:57 UTC, mahbubul14 requested changes
Hi @Bushido-brown ,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [ ] In the `README` file, Kindly update the "Getting Started" section. This should be an example of how you may give instructions on setting up your project locally.

- [ ] Kindly check the inline comments under the review for more suggestions. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Github flow used properly.

### Optional suggestions

- [ ] The commit message should be written in the imperative tense and the first letter also should be capitalized. `Ex: "Fix bug" instead of "fix bug".` [For more details.](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-05-12 23:57 UTC, mahbubul14 commented on index.html
>                src="img/Snapshoot-Portfolio.png"
- [ ] Please do not commit old pieces of code as inline comments. They will make your project look messy. If you need to review a previous version of your code, you can always use git history. Kindly remove the inline comments from your code(**line 84 - 191**). :+1:

2022-05-12 23:57 UTC, mahbubul14 commented on index.html
>        <div class="works" id="portfolio">
[ ] Currently, your design is not matched with the Figma design. Kindly reduce the gap between the main page and the pop-up and try to match with the Figma design. :+1:

Your design             |  Figma Design
:-------------------------:|:-------------------------:
![y2](https://user-images.githubusercontent.com/70483835/168184431-92c59b8b-cb8b-4c1b-a23e-b047350da50e.png) | ![f2](https://user-images.githubusercontent.com/70483835/168184425-3a4e8360-5f43-4e4b-8639-c5cf75ee23bb.png)


- [ ] Kindly do the adjustment for mobile also. :+1:

Your design             |  Figma Design
:-------------------------:|:-------------------------:
![y3](https://user-images.githubusercontent.com/70483835/168185038-d059a776-4cc0-4a1f-b393-54c848f816a6.png) | ![f3](https://user-images.githubusercontent.com/70483835/168185032-5b3f952a-78c0-4238-9929-e1c31e61040f.png)

- [ ] Please try to match the font color according to the Figma design. :+1:

Your design             |  Figma Design
:-------------------------:|:-------------------------:
![y1](https://user-images.githubusercontent.com/70483835/168185212-0b0bc1a3-689c-450d-b8ea-0a3dc0cd3ec9.png) | ![f1](https://user-images.githubusercontent.com/70483835/168185210-3cfed4cc-4d57-4dac-9299-6b5535226550.png)

2022-05-13 03:15 UTC, CollinsTatang approved these changes
# Approved 👏  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-13 17:21 UTC, merged